export const serviceVisuals = [
  {
    slug: "digital-marketing",
    image: "/assets/services/digital-marketing.91369696.webp",
    alt: "A person reviewing social media analytics on a smartphone",
    credit: "Swello",
    source: "https://unsplash.com/photos/checking-data-analytics-on-a-phone-YRKUwWH_zL8",
    steps: ["Understand the audience", "Plan content and channels", "Review campaign signals"],
    scene: "From first impression to a measurable conversation.",
  },
  {
    slug: "data-analytics",
    image: "/assets/services/data-analytics.0ad942f8.webp",
    alt: "Two colleagues discussing information on a laptop",
    credit: "Vitaly Gariev",
    source: "https://unsplash.com/photos/two-colleagues-discussing-data-on-a-laptop-screen-1FzEg5g7vt0",
    steps: ["Bring data together", "Explore trends", "Share a clearer view"],
    scene: "Give teams a clearer view of what is happening.",
  },
  {
    slug: "business-strategy",
    image: "/assets/services/business-strategy.334766d3.webp",
    alt: "Business colleagues planning together at a laptop",
    credit: "Vitaly Gariev",
    source: "https://unsplash.com/photos/two-men-looking-at-a-laptop-together-MSTL7-5avQo",
    steps: ["Define the challenge", "Map the opportunity", "Choose the next move"],
    scene: "Turn a business challenge into a practical direction.",
  },
  {
    slug: "website-development",
    image: "/assets/services/website-development.92709a97.webp",
    alt: "Developer writing code on a laptop",
    credit: "Alicia Christin Gerald",
    source: "https://unsplash.com/photos/developer-typing-code-on-a-laptop-screen-xaWYIbNIOdw",
    steps: ["Shape the experience", "Build responsive pages", "Launch and refine"],
    scene: "A digital front door built around real visitors.",
  },
  {
    slug: "app-development",
    image: "/assets/services/app-development.8263d561.webp",
    alt: "A person testing a mobile application beside a code editor",
    credit: "Fahim Muntashir",
    source: "https://unsplash.com/photos/a-person-holding-a-cell-phone-in-front-of-a-laptop-v-FOvoL3onk",
    steps: ["Frame the use case", "Design key journeys", "Develop and improve"],
    scene: "A useful experience that fits in someone's hand.",
  },
  {
    slug: "startup-innovation",
    image: "/assets/services/startup-innovation.cbc1c49d.webp",
    alt: "A team brainstorming with notes on a glass wall",
    credit: "Vitaly Gariev",
    source: "https://unsplash.com/photos/team-brainstorming-with-colorful-sticky-notes-on-glass-euNzbqwIIUI",
    steps: ["Test the idea", "Prioritize an MVP", "Learn from the launch"],
    scene: "Move a new idea toward its first useful version.",
  },
  {
    slug: "ecommerce",
    image: "/assets/services/ecommerce.9f3b453d.webp",
    alt: "Small business owner checking products and orders beside a laptop",
    credit: "Rifki Kurniawan",
    source: "https://unsplash.com/photos/woman-checking-package-with-phone-near-laptop-and-boxes-k63Or81F8-M",
    steps: ["Organize the catalog", "Simplify shopping", "Connect the operation"],
    scene: "Bring storefront and everyday operations together.",
  },
] as const;
