import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ContactBand, PageIntro } from "@/components/SiteFrame";
import { approach, brands } from "@/lib/site";

export const metadata: Metadata = { title: "About Us", description: "Learn about NRE TechOne Solutions, our mission, approach and technology, commerce and innovation ecosystem in Wyoming, USA." };

export default function About() {
  return <><PageIntro eyebrow="ABOUT NRE TECHONE SOLUTIONS" title="Technology with a business purpose." description="Based in Wyoming, WY, USA, we work with startups, entrepreneurs and organizations seeking practical digital and business solutions." />
    <section className="section container about-story"><div><p className="eyebrow">ONE PLATFORM. MULTIPLE SOLUTIONS.</p><h2>Ideas work better when the pieces connect.</h2><p>NRE TechOne Solutions brings development, digital marketing, data analytics, business strategy, e-commerce and innovation support together under one umbrella. We begin with the requirement behind each project and shape the combination of services around it.</p><Link href="/solutions" className="inline-link">See our solutions <span aria-hidden="true">→</span></Link></div><div className="story-image"><Image src="/assets/mobile-design-session.webp" alt="Illustrative scene of developers reviewing a mobile application prototype" fill sizes="(max-width: 800px) 100vw, 50vw" /><span>IDEAS INTO WORKING EXPERIENCES</span></div></section>
    <section className="dark-section"><div className="container two-column"><div><p className="eyebrow">OUR VISION</p><h2>A connected ecosystem for useful ideas.</h2><p>We aim to bring technology and business solutions together so ideas can become opportunities and support sustainable growth.</p></div><div><p className="eyebrow">OUR MISSION</p><h2>Practical technology, made more accessible.</h2><p>We focus on understanding the business need, then developing digital solutions aligned with that objective from early planning through implementation and improvement.</p></div></div></section>
    <section className="section container"><div className="section-top"><div><p className="eyebrow">WHAT WE BELIEVE</p><h2>Principles behind the work.</h2></div></div><div className="values-list"><div><span>01</span><h3>Innovation</h3><p>Stay open to new ideas and better ways to solve a problem.</p></div><div><span>02</span><h3>Practical technology</h3><p>Build for a real requirement and a clear business objective.</p></div><div><span>03</span><h3>Continuous improvement</h3><p>Review what the solution achieves and improve it over time.</p></div><div><span>04</span><h3>Long-term partnerships</h3><p>Work through clear communication and consistent delivery.</p></div></div></section>
    <section className="approach-section"><div className="container"><p className="eyebrow">OUR APPROACH</p><h2>From first conversation to what comes next.</h2><div className="approach-steps">{approach.map(step => <div key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.body}</p></div>)}</div></div></section>
    <section className="section container"><div className="section-top"><div><p className="eyebrow">OUR ECOSYSTEM</p><h2>Technology. Commerce. Innovation.</h2></div><p>Three initiatives with different focuses share one broader vision.</p></div><div className="brand-preview-grid">{brands.map(brand => <div key={brand.name}><span>{brand.number}</span><h3>{brand.name}</h3><p>{brand.description}</p><small>{brand.line}</small></div>)}</div><div className="section-end"><Link href="/brands" className="inline-link">Explore our brands <span aria-hidden="true">→</span></Link></div></section>
    <ContactBand title="Let's discuss your next idea." />
  </>;
}
