import { images, imageSizes, heroBlurDataURL } from "@/lib/images";
import Image from "next/image";
import Link from "next/link";
import { ContactBand } from "@/components/SiteFrame";
import { brands, coreServices } from "@/lib/site";
import { serviceVisuals } from "@/lib/serviceVisuals";

const featuredSlugs = ["website-development", "app-development", "business-strategy"];

export default function Home() {
  return <>
    <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Technology | Commerce | Innovation</p><h1>One platform.<br /><em>Multiple solutions.</em></h1><p className="lead">We bring technology, business strategy, digital transformation and commerce together to turn ideas into practical solutions.</p><div className="hero-actions"><Link href="/solutions" className="button button-dark">Explore our solutions <span aria-hidden="true">↗</span></Link><Link href="/contact" className="inline-link">Talk to us <span aria-hidden="true">→</span></Link></div><p className="hero-aside">Based in Wyoming, USA · Working with businesses worldwide</p></div><div className="hero-image"><Image src={images.hero} alt="Illustrative scene of a team planning a digital product" fill sizes={imageSizes.hero} priority fetchPriority="high" placeholder="blur" blurDataURL={heroBlurDataURL} /><div className="hero-image-label"><span>INNOVATING THE FUTURE</span><strong>Ideas become useful experiences.</strong></div></div></div></section>
    <section className="statement-strip" aria-label="How our capabilities connect"><div className="container"><span>Strategy</span><i>✳</i><span>Design</span><i>✳</i><span>Technology</span><i>✳</i><span>Data</span><i>✳</i><span>Growth</span></div></section>
    <section className="section container"><div className="section-top"><div><p className="eyebrow">OUR CORE SOLUTIONS</p><h2>Technology that moves<br />business forward.</h2></div><p>Different needs call for different capabilities. Choose one service or connect several around your business goal.</p></div><div className="home-service-stories">{featuredSlugs.map(slug => { const service = coreServices.find(item => item.slug === slug)!; const visual = serviceVisuals.find(item => item.slug === slug)!; return <Link href={`/services#${slug}`} className="home-story" key={slug}><div className="home-story-image"><Image src={visual.image} alt={visual.alt} fill sizes={slug === "app-development" ? imageSizes.appCard : imageSizes.serviceCard} className={slug === "app-development" ? "app-photo" : undefined} /><span>EXPLORE SERVICE <b aria-hidden="true">↗</b></span></div><div className="home-story-copy"><span>{service.number} / 07</span><h3>{service.title}</h3><p>{visual.scene}</p></div></Link>; })}</div><div className="home-services">{coreServices.filter(service => !featuredSlugs.includes(service.slug)).map(service => <Link href={`/services#${service.slug}`} className="home-service" key={service.slug}><span>{service.number}</span><h3>{service.title}</h3><p>{service.brief}</p><b aria-hidden="true">↗</b></Link>)}</div><p className="home-photo-note">Service photography is illustrative; pictured people are not identified as NRE personnel or clients.</p><div className="section-end"><Link href="/services" className="inline-link">Explore all seven services <span aria-hidden="true">→</span></Link></div></section>
    <section className="feature-section"><div className="container feature-grid"><div className="feature-visual" aria-hidden="true"><span className="feature-pulse" /><div className="message-card"><small>CUSTOMER MESSAGE</small><p>I&apos;d like to book an appointment.</p></div><div className="flow-line" /><div className="reply-card"><small>AUTOMATED FLOW</small><p>Let&apos;s find a time that works for you.</p></div><span className="feature-note">ILLUSTRATIVE WORKFLOW</span></div><div className="feature-copy"><p className="eyebrow">CONNECTED COMMUNICATION</p><h2>Customer conversations, connected to your business.</h2><p>Our WhatsApp Business and API solutions can connect messaging with your CRM, website or business workflows. Explore chatbots, reminders and customer support flows built around a clear use case.</p><Link href="/whatsapp-solutions" className="button button-outline">Explore WhatsApp solutions <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="section container"><div className="section-top"><div><p className="eyebrow">FROM IDEA TO IMPACT</p><h2>Built around the real requirement.</h2></div><p>We learn how your business works, choose a practical direction, then develop and improve the experience with you.</p></div><div className="principle-grid"><div><span>01</span><h3>Understand the goal</h3><p>Start with the business problem, the people using the solution and what success should look like.</p></div><div><span>02</span><h3>Connect the capabilities</h3><p>Bring together strategy, technology, data, marketing or commerce when the work calls for them.</p></div><div><span>03</span><h3>Keep improving</h3><p>Review what works and identify the next useful change as the business evolves.</p></div></div></section>
    <section className="brands-preview"><div className="container"><div className="section-top"><div><p className="eyebrow">OUR ECOSYSTEM</p><h2>One vision. Three initiatives.</h2></div><Link href="/brands" className="inline-link">Meet our brands <span aria-hidden="true">→</span></Link></div><div className="brand-preview-grid">{brands.map(brand => <div key={brand.name}><span>{brand.number}</span><h3>{brand.name}</h3><p>{brand.focus}</p><small>{brand.line}</small></div>)}</div></div></section>
    <ContactBand title="Let's build what's next." body="Have an idea, a business challenge or a digital project? Let's explore a practical solution together." />
  </>;
}
