import Image from "next/image";

const services = [
  { id: "software", n: "01", icon: "⌘", label: "Custom software development", title: "Software shaped around your business.", body: "From internal tools to customer-facing products, we design and develop software around the way your business works and where it wants to go.", tags: ["Web applications", "Business software", "Product development"] },
  { id: "mobile", n: "02", icon: "▣", label: "Mobile applications", title: "Your idea, made for the small screen.", body: "Create mobile experiences that make it easier for customers and teams to connect, act, and get things done on the go.", tags: ["Mobile app design", "App development", "User experience"] },
  { id: "platforms", n: "03", icon: "◈", label: "Web & e-commerce", title: "Digital experiences built to work harder.", body: "Build a stronger online presence with websites and commerce experiences designed for real users and business goals.", tags: ["Websites", "E-commerce platforms", "Digital experiences"] },
  { id: "talent", n: "04", icon: "✳", label: "IT talent & staffing", title: "The right people change everything.", body: "Build the team behind your next big move. We connect businesses with people whose skills and ambition fit the work ahead.", tags: ["Onshore recruitment", "Offshore recruitment", "Staffing solutions"] },
  { id: "consulting", n: "05", icon: "↗", label: "Strategy & consulting", title: "Clarity creates momentum.", body: "Move from a complicated challenge to a practical way forward with business thinking grounded in your goals.", tags: ["Business strategy", "Data analytics", "Startup & innovation"] },
  { id: "digital", n: "06", icon: "◉", label: "Digital marketing", title: "Make your next move visible.", body: "Bring your brand and customers closer with digital marketing informed by your audience and your growth goals.", tags: ["Digital marketing", "Online presence", "Growth strategy"] },
];

function Logo() {
  return <a className="brand" href="#top" aria-label="NRE TechOne Solutions, back to top"><span className="brand-mark"><Image src="/assets/nre-logo.jpeg" alt="" width={80} height={80} priority /></span><span className="brand-type"><strong>NRE<span>.</span></strong><small>TECHONE SOLUTIONS</small></span></a>;
}

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span />{children}</p>; }

export default function Home() {
  return <div id="top">
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><div className="shell header-inner"><Logo /><nav className="desktop-nav" aria-label="Main navigation"><a href="#services">What we do</a><a href="#about">Who we are</a><a href="#approach">How we work</a></nav><a className="header-cta" href="#contact">Let&apos;s connect <span>↗</span></a><details className="mobile-menu"><summary>Menu <span>☰</span></summary><nav aria-label="Mobile navigation"><a href="#services">What we do</a><a href="#about">Who we are</a><a href="#approach">How we work</a><a href="#contact">Let&apos;s connect</a></nav></details></div></header>
    <main id="main">
      <section className="hero shell" aria-labelledby="hero-title"><div className="hero-copy"><Eyebrow>SOFTWARE · MOBILE · PEOPLE</Eyebrow><h1 id="hero-title">Technology built for <em>what&apos;s next.</em></h1><p className="hero-lede">We turn business ideas into useful software and mobile experiences, then connect the people and strategy to help them grow.</p><div className="hero-actions"><a className="button" href="#services">Explore our services <span>↗</span></a><a className="text-link" href="#contact">Talk about your project <span>→</span></a></div><p className="hero-footnote"><i /> Based in India. Working worldwide.</p></div><div className="hero-art" aria-hidden="true"><div className="art-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="art-core"><span>NRE</span><small>IDEAS IN MOTION</small></div><div className="art-chip chip-one"><span>01</span> SOFTWARE <b>↗</b></div><div className="art-chip chip-two"><span>02</span> MOBILE <b>↗</b></div><div className="art-chip chip-three"><span>03</span> PEOPLE <b>↗</b></div><div className="art-star star-one">✳</div><div className="art-star star-two">✳</div><div className="art-caption">BUILD / CONNECT / GROW</div></div></section>
      <div className="marquee"><div><span>Software with purpose</span><b>✳</b><span>Mobile with impact</span><b>✳</b><span>People with potential</span><b>✳</b><span>Software with purpose</span><b>✳</b></div></div>
      <section className="section shell" id="services" aria-labelledby="services-title"><div className="section-heading"><div><Eyebrow>01 / WHAT WE DO</Eyebrow><h2 id="services-title">Build it. Connect it.<br /><em>Grow it.</em></h2></div><p>Software and mobile development are at the heart of what we do, supported by talent, consulting, and digital marketing for the wider business journey.</p></div><div className="service-list">{services.map(s => <article className="service-row" id={s.id} key={s.id}><span className="service-index">{s.n} / 06</span><span className="service-icon" aria-hidden="true">{s.icon}</span><div className="service-main"><p className="service-label">{s.label}</p><h3>{s.title}</h3><p>{s.body}</p><div className="service-tags">{s.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><a className="service-arrow" href="#contact" aria-label={`Discuss ${s.label} with NRE`}>↗</a></article>)}</div></section>
      <section className="about" id="about" aria-labelledby="about-title"><div className="shell about-grid"><div className="about-art" aria-hidden="true"><span className="about-top">A DIFFERENT KIND OF PARTNER</span><span className="about-star">✳</span><span className="about-bottom">INDIA ↔ WORLDWIDE</span></div><div className="about-copy"><Eyebrow>02 / WHO WE ARE</Eyebrow><h2 id="about-title">Built for the <em>next chapter.</em></h2><p className="about-lead">Good technology works better when it is connected to the people and purpose behind it.</p><p>NRE TechOne Solutions is a growing company offering software development, mobile applications, and web experiences alongside staffing, consulting, and digital marketing. With operations in India and worldwide, we bring these capabilities together around each business&apos;s goals.</p><a className="text-link" href="#approach">The way we work <span>→</span></a></div></div></section>
      <section className="section shell" id="approach" aria-labelledby="approach-title"><div className="section-heading"><div><Eyebrow>03 / HOW WE WORK</Eyebrow><h2 id="approach-title">Good work begins<br /><em>with understanding.</em></h2></div><p>Whether the need is a product, a team, or a digital strategy, we start with the problem worth solving.</p></div><div className="steps"><article><span>01</span><i>◎</i><h3>Discover.</h3><p>We learn about your users, goals, and practical constraints before shaping a plan.</p></article><article><span>02</span><i>↗</i><h3>Build together.</h3><p>We bring the right technical and business capabilities to the work.</p></article><article><span>03</span><i>✳</i><h3>Keep improving.</h3><p>We focus on useful outcomes and relationships built to last.</p></article></div></section>
      <section className="contact" id="contact" aria-labelledby="contact-title"><div className="shell contact-inner"><div><Eyebrow>THE NEXT MOVE STARTS HERE</Eyebrow><h2 id="contact-title">Let&apos;s make<br /><em>something happen.</em></h2><p>Have a software idea, a mobile app in mind, a hiring challenge, or a growth goal? Tell us what you&apos;re working on.</p></div><div className="contact-card"><span>✳</span><h3>Start a conversation</h3><p>Share your project, business needs, or the kind of support you&apos;re looking for.</p><div className="contact-methods"><a href="mailto:info@nretech.com?subject=Let's%20talk%20about%20working%20with%20NRE"><span>Email us</span><strong>info@nretech.com</strong><b aria-hidden="true">↗</b></a><a href="tel:3201541558"><span>Call us</span><strong>320 154 1558</strong><b aria-hidden="true">↗</b></a></div></div></div></section>
    </main>
    <footer className="footer"><div className="shell footer-top"><Logo /><p>Software, mobile experiences, and the people to move business forward.</p><a href="#top">Back to top ↑</a></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} NRE TechOne Solutions</span><span>India · Worldwide</span></div></footer>
  </div>;
}
